/**
 * Mapping between recommendation codes and article IDs
 * This is a deterministic mapping that guides users to relevant learning materials
 * based on the adaptation recommendations generated by the backend.
 */

export const RECOMMENDATION_ARTICLE_MAP: Record<string, string[]> = {
  SIMPLIFY_HABIT: ['habit-small-steps', 'reduce-friction'],
  ADJUST_CUE: ['fix-your-cues'],
  REDUCE_TARGET: ['habit-small-steps', 'reduce-friction'],
  INCREASE_SUPPORT: ['fix-your-cues', 'reduce-reminder-dependence'],
  REVIEW_REMINDER_DEPENDENCE: ['reduce-reminder-dependence', 'fix-your-cues'],
  BUILD_CONSISTENCY: ['build-consistency', 'reduce-friction'],
  CELEBRATE_CONSISTENCY: ['build-consistency'],
};

/**
 * Get article IDs for a recommendation code.
 * Falls back to general articles if the code is not found.
 */
export function getArticleIdsForRecommendation(
  recommendationCode: string,
): string[] {
  return (
    RECOMMENDATION_ARTICLE_MAP[recommendationCode] || [
      'build-consistency',
      'habit-small-steps',
    ]
  );
}
